var searchData=
[
  ['dashboard_0',['dashboard',['..//github/workspace/platform/statistic/README.md#autotoc_md65',1,'Import Nexres dynamic dashboard.'],['..//github/workspace/platform/statistic/README.md#autotoc_md55',1,'Start the dashboard']]],
  ['data_1',['data',['../df/d64/structresdb_1_1QueueItem.html#abf80ccdb8babb39e0e8bcea057da0e63',1,'resdb::QueueItem']]],
  ['data_20into_20nexres_2',['Set random data into nexres',['..//github/workspace/platform/statistic/README.md#autotoc_md69',1,'']]],
  ['data_5fcomm_2eh_3',['data_comm.h',['../d2/d9a/data__comm_8h.html',1,'']]],
  ['data_5flen_4',['data_len',['../dd/dd6/structresdb_1_1DataInfo.html#a91477e9f44ed3729c8ba2860bb90bcc1',1,'resdb::DataInfo']]],
  ['data_5fqueue_5f_5',['data_queue_',['../dc/db0/classresdb_1_1CheckPointManager.html#afb4eac9eaae472ee7464f09b74162ccd',1,'resdb::CheckPointManager']]],
  ['datainfo_6',['DataInfo',['../dd/dd6/structresdb_1_1DataInfo.html',1,'resdb::DataInfo'],['../dd/dd6/structresdb_1_1DataInfo.html#a14a877c9faa5cdd4d737e126af735a57',1,'resdb::DataInfo::DataInfo()']]],
  ['deploy_20kv_20service_7',['Deploy KV Service',['..//github/workspace/scripts/deploy/README.md#autotoc_md99',1,'']]],
  ['deploy_20resilientdb_8',['Build and Deploy ResilientDB',['..//github/workspace/README.md#autotoc_md81',1,'']]],
  ['deploy_20via_20docker_9',['Deploy via Docker',['..//github/workspace/README.md#autotoc_md95',1,'']]],
  ['deploycontract_10',['DeployContract',['../d6/d7d/classresdb_1_1contract_1_1ContractManager.html#a14ddd808a0665b5f2ee79c05308bf699',1,'resdb::contract::ContractManager::DeployContract()'],['../d9/dfa/classresdb_1_1contract_1_1ContractClient.html#a7d414fceddccb9146ceff3d34198b96c',1,'resdb::contract::ContractClient::DeployContract(const std::string &amp;caller_address, const std::string &amp;contract_name, const std::string &amp;contract_path, const std::vector&lt; std::string &gt; &amp;init_params)'],['../d9/dfa/classresdb_1_1contract_1_1ContractClient.html#a7d414fceddccb9146ceff3d34198b96c',1,'resdb::contract::ContractClient::DeployContract(const std::string &amp;caller_address, const std::string &amp;contract_name, const std::string &amp;contract_path, const std::vector&lt; std::string &gt; &amp;init_params)'],['../d5/df9/classContractClient.html#a7d414fceddccb9146ceff3d34198b96c',1,'ContractClient::DeployContract(const std::string &amp;caller_address, const std::string &amp;contract_name, const std::string &amp;contract_path, const std::vector&lt; std::string &gt; &amp;init_params)'],['../d5/df9/classContractClient.html#a7d414fceddccb9146ceff3d34198b96c',1,'ContractClient::DeployContract(const std::string &amp;caller_address, const std::string &amp;contract_name, const std::string &amp;contract_path, const std::vector&lt; std::string &gt; &amp;init_params)'],['../d6/dff/contract__tools_8cpp.html#ac5f318a4e5f462ab6986adc27d36b95d',1,'DeployContract(ContractClient *client, const std::string &amp;caller_address, const std::string &amp;contract_name, const std::string &amp;contract_path, const std::vector&lt; std::string &gt; &amp;init_params):&#160;contract_tools.cpp'],['../df/da0/contract__service__tools_8cpp.html#ac5f318a4e5f462ab6986adc27d36b95d',1,'DeployContract(ContractClient *client, const std::string &amp;caller_address, const std::string &amp;contract_name, const std::string &amp;contract_path, const std::vector&lt; std::string &gt; &amp;init_params):&#160;contract_service_tools.cpp']]],
  ['deployed_20kv_20service_11',['Testing deployed KV Service',['..//github/workspace/scripts/deploy/README.md#autotoc_md100',1,'']]],
  ['deployment_20script_12',['Deployment Script',['..//github/workspace/README.md#autotoc_md94',1,'']]],
  ['description_13',['Description',['..//github/workspace/api/README.md#autotoc_md1',1,'']]],
  ['development_3a_14',['Prometheus metrics development:',['..//github/workspace/platform/statistic/README.md#autotoc_md67',1,'']]],
  ['diagram_15',['GeoBFT Consensus Structure Diagram',['..//github/workspace/platform/consensus/ordering/geo_pbft/README.md#autotoc_md40',1,'']]],
  ['dispatch_16',['Dispatch',['../da/d19/classresdb_1_1ConsensusManager.html#aded3d44b3131103f6c8849491fa4e346',1,'resdb::ConsensusManager']]],
  ['docker_17',['Deploy via Docker',['..//github/workspace/README.md#autotoc_md95',1,'']]],
  ['documentation_3a_18',['Online Documentation:',['..//github/workspace/README.md#autotoc_md77',1,'']]],
  ['download_20and_20install_20grafana_19',['Download and Install grafana',['..//github/workspace/monitoring/README.md#autotoc_md38',1,'']]],
  ['download_20node_5fexporter_20',['Download node_exporter',['..//github/workspace/monitoring/README.md#autotoc_md37',1,'']]],
  ['download_20prometheus_21',['Download Prometheus',['..//github/workspace/monitoring/README.md#autotoc_md36',1,'']]],
  ['downloads_3a_22',['Downloads:',['..//github/workspace/README.md#autotoc_md74',1,'']]],
  ['duplicate_5fmanager_2ecpp_23',['duplicate_manager.cpp',['../df/dd5/duplicate__manager_8cpp.html',1,'']]],
  ['duplicate_5fmanager_2eh_24',['duplicate_manager.h',['../d7/dd0/duplicate__manager_8h.html',1,'']]],
  ['duplicate_5fmanager_5f_25',['duplicate_manager_',['../dd/d4b/classresdb_1_1Commitment.html#af38e8574b68da0c20576d31ad60e5ef8',1,'resdb::Commitment::duplicate_manager_'],['../d1/db2/classresdb_1_1ViewChangeManager.html#a10f5e377daad2b2fbb2c0394f71c8d8c',1,'resdb::ViewChangeManager::duplicate_manager_']]],
  ['duplicatemanager_26',['DuplicateManager',['../d6/da0/classresdb_1_1DuplicateManager.html',1,'resdb::DuplicateManager'],['../d6/da0/classresdb_1_1DuplicateManager.html#a437d8fdb66cd62ea669522338b139f33',1,'resdb::DuplicateManager::DuplicateManager()']]],
  ['dynamic_20dashboard_27',['Import Nexres dynamic dashboard.',['..//github/workspace/platform/statistic/README.md#autotoc_md65',1,'']]]
];
